apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/Lesrac/argocd-apps.git
  repository.credentials: |
    - url: https://github.com
      passwordSecret:
        name: github
        key: password
      usernameSecret:
        name: github
        key: username