apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part-of-services
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ns2
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps
    repoURL: https://github.com/Lesrac/argocd-intermediate-app-of-apps.git
    targetRevision: {{ .Values.spec.source.targetRevision }}